### ISSUE TITLE
List showing nothing, but random shows articles?

### ISSUE THREAD

**Issue by kergoth** [rakanalh/pocket-cli#2]

**Comment by rakanalh** [comment]
Hello @kergoth, 

I am assuming you did the following:
1. pocket-cli configure
2. pocket-cli fetch

if so, could you double check ~/.pocket-index file?

**Comment by kergoth** [comment]
```
~ › cat ~/.pocket-index | wc -l
     335
~ › pocket-cli list
~ ›
```

**Comment by kergoth** [comment]
And yep, did both configure and multiple fetches.

**Comment by rakanalh** [comment]
hmm.. strange. Can i have a look at a sample of that file? I need to run the sample on my version to be able to debug this.

**Comment by kergoth** [comment]
I just tested with everything removed but the latest link, still doesn't list anything here:

```
url,reading_time,id,word_count,title
https://github.com/danthedeckie/simpleeval,1.0,590455802,893,danthedeckie/simpleeval
```

**Comment by rakanalh** [comment]
Thanks... i was able to reproduce the issue. I'll have a look!

**Comment by kergoth** [comment]
Np, thanks for your work on this. pocket-cli meets a definite need. pockyt existed, but has a really weird cli interface.

**Comment by rakanalh** [comment]
Could you please clone the repository, and execute the following:

```
> rm ~/.pocket-index
> cd [clone-dir]
> git checkout float_div
> python -m pocket_cli.cli fetch
> python -m pocket_cli.cli list
```

I've tested this on your sample data but i want to make sure it works on your side as well :)

**Comment by kergoth** [comment]
I had to also edit .pocket-config to wipe the last fetch stamp, otherwise it wouldn't fetch anything, since nothing new was added since the last fetch, but after that, it re-fetched and list works. Thanks for your work on this.

**Comment by rakanalh** [comment]
Yup, sorry i forgot to mention that. Glad it's working for you. I'll merge it and release it on Pypi tonight.
Thank you for reporting the issue.

**Comment by rakanalh** [comment]
FYI, 0.1.3 including fixes for both of your issue reports, has been uploaded.
