### ISSUE TITLE
Please provide sensible defaults

### ISSUE THREAD

**Issue by kseistrup** [rakanalh/pocket-cli#7]
When configuring Pocket-CLI I was asked about (1) how to sort articles and (2) my reading speed. However, I was given no clues to which options were available for sorting and I have no idea how many words per minute I am able to read. So I entered some rubbish for question 1 (and found out that the options were `id` and `reading_time`) and off-handedly guessed at 300 wpm for question 2.

It would be helpful if new users were presented with (1) possible sorting fields, and (2) some examples of reading speed, e.g.  “50 (slow), 200 (medium), 1000 (fast)” (I'm just grabbing some numbers out of thin air here).

**Comment by rakanalh** [comment]
Excellent point! I'll see if i can add more context to prompts
